#!C:\Users\huazh\OneDrive - Georgia Institute of Technology\Documents\CS 4420\evadb-stock-forecasting\evadb-venv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
